Repository ministryofjustice/check-financial-eligibility-partner, pull requests merged in 2022-11, with the labels that each got.

#6 EL-464: partner data model
  app/models/applicant_capital_summary.rb
  app/models/applicant_disposable_income_summary.rb
  app/models/applicant_employment.rb
  app/models/applicant_gross_income_summary.rb
  app/models/assessment.rb
  app/models/partner.rb
  app/models/partner_capital_summary.rb
  app/models/partner_disposable_income_summary.rb
  app/models/partner_employment.rb
  app/models/partner_gross_income_summary.rb
  app/services/decorators/v5/proceeding_types_result_decorator.rb
  db/migrate/20221114092809_create_partners.rb
  db/schema.rb
  spec/services/creators/capitals_creator_spec.rb
Labels: Ready for review

#12 EL-465 partner endpoint: second attempt at merging
  app/controllers/partner_financials_controller.rb
  app/services/creators/capitals_creator.rb
  app/services/creators/employments_creator.rb
  app/services/creators/irregular_income_creator.rb
  app/services/creators/partner_financials_creator.rb
  app/services/creators/partner_properties_creator.rb
  app/services/creators/regular_transactions_creator.rb
  app/services/creators/state_benefits_creator.rb
  app/services/creators/vehicle_creator.rb
  config/routes.rb
  public/schemas/additional_properties.json.erb
  public/schemas/partner.json.erb
  spec/factories/partner_factory.rb
  spec/fixtures/partner_financials.json
  spec/requests/swagger_docs/v5/partner_financials_spec.rb
  spec/services/creators/partner_financials_creator_spec.rb
  swagger/v5/swagger.yaml
Labels: Approved

#13 El 466 partner calculations
  app/models/cash_transaction.rb
  app/models/eligibility/gross_income.rb
  app/services/assessors/gross_income_assessor.rb
  app/services/calculators/employment_income_calculator.rb
  app/services/calculators/housing_costs_calculator.rb
  app/services/calculators/multiple_employments_calculator.rb
  app/services/calculators/state_benefits_calculator.rb
  app/services/collators/childcare_collator.rb
  app/services/collators/dependants_allowance_collator.rb
  app/services/collators/disposable_income_collator.rb
  app/services/collators/gross_income_collator.rb
  app/services/collators/housing_costs_collator.rb
  app/services/collators/legal_aid_collator.rb
  app/services/collators/maintenance_collator.rb
  app/services/collators/outgoings_collator.rb
  app/services/collators/regular_income_collator.rb
  app/services/concerns/transactions.rb
  app/services/workflows/non_passported_workflow.rb
  spec/models/cash_transaction_spec.rb
  spec/services/assessors/gross_income_assessor_spec.rb
  spec/services/calculators/employment_income_calculator_spec.rb
  spec/services/calculators/housing_costs_calculator_spec.rb
  spec/services/calculators/multiple_employments_calculator_spec.rb
  spec/services/calculators/state_benefits_calculator_spec.rb
  spec/services/collators/childcare_collator_spec.rb
  spec/services/collators/dependants_allowance_collator_spec.rb
  spec/services/collators/disposable_income_collator_spec.rb
  spec/services/collators/gross_income_collator_spec.rb
  spec/services/collators/housing_costs_collator_spec.rb
  spec/services/collators/legal_aid_collator_spec.rb
  spec/services/collators/maintenance_collator_spec.rb
  spec/services/collators/outgoings_collator_spec.rb
  spec/services/collators/regular_income_collator_spec.rb
  spec/services/decorators/v5/disposable_income_result_decorator_spec.rb
  spec/services/workflows/non_passported_workflow_spec.rb
  spec/spec_helper.rb
Labels: Approved

#8 EL-467: output payload
  app/services/decorators/v5/assessment_decorator.rb
  app/services/decorators/v5/capital_decorator.rb
  app/services/decorators/v5/capital_result_decorator.rb
  app/services/decorators/v5/disposable_income_decorator.rb
  app/services/decorators/v5/disposable_income_result_decorator.rb
  app/services/decorators/v5/gross_income_decorator.rb
  app/services/decorators/v5/gross_income_result_decorator.rb
  app/services/decorators/v5/result_summary_decorator.rb
  spec/services/decorators/v5/assessment_decorator_spec.rb
  spec/services/decorators/v5/capital_result_decorator_spec.rb
  spec/services/decorators/v5/disposable_income_result_decorator_spec.rb
  spec/services/decorators/v5/gross_income_decorator_spec.rb
  spec/services/decorators/v5/gross_income_result_decorator_spec.rb
Labels: Approved

#17 El 455 cfep prod deploy
  .circleci/config.yml
  bin/uat_deploy
  deploy/helm/values-production.yaml
  deploy/helm/values-staging.yaml
Labels: Approved

#18 add sentry dsn for all envs
  deploy/helm/values-production.yaml
  deploy/helm/values-staging.yaml
  deploy/helm/values-uat.yaml
Labels: Approved

#15 EL-485 - remove housing costs cap if applicant has a partner
  app/lib/applicant_or_partner_wrapper.rb
  app/lib/person_wrapper.rb
  app/services/assessors/disposable_income_assessor.rb
  app/services/calculators/housing_costs_calculator.rb
  app/services/calculators/income_contribution_calculator.rb
  app/services/collators/childcare_collator.rb
  app/services/collators/disposable_income_collator.rb
  app/services/collators/housing_costs_collator.rb
  app/services/collators/outgoings_collator.rb
  app/services/collators/regular_income_collator.rb
  app/services/collators/regular_outgoings_collator.rb
  app/services/concerns/monthly_equivalent_calculatable.rb
  app/services/workflows/non_passported_workflow.rb
  spec/factories/cash_transaction_category_factory.rb
  spec/factories/employment_factory.rb
  spec/factories/irregular_income_payment_factory.rb
  spec/factories/regular_transaction_factory.rb
  spec/services/assessors/disposable_income_assessor_spec.rb
  spec/services/calculators/housing_costs_calculator_spec.rb
  spec/services/collators/childcare_collator_spec.rb
  spec/services/collators/housing_costs_collator_spec.rb
  spec/services/collators/outgoings_collator_spec.rb
  spec/services/collators/regular_outgoings_collator_spec.rb
  spec/services/workflows/non_passported_workflow_spec.rb
Labels: Approved

#16 EL-486 add partner allowance threshold to disposable income calculation
  app/services/workflows/non_passported_workflow.rb
  config/thresholds/2022-04-11.yml
  spec/factories/employment_factory.rb
  spec/factories/partner_factory.rb
  spec/services/workflows/non_passported_workflow_spec.rb
Labels: Approved

#22 EL-490: Assess childcare eligibility when considering childcare costs
  app/services/collators/childcare_collator.rb
  app/services/collators/regular_outgoings_collator.rb
  app/services/concerns/childcare_eligibility.rb
  app/services/workflows/non_passported_workflow.rb
  lib/integration_helpers/test_case/applicant.rb
  spec/factories/dependant_factory.rb
  spec/services/collators/regular_outgoings_collator_spec.rb
Labels: question

#21 EL-487 partner capital calculations
  app/models/eligibility/capital.rb
  app/services/assessors/capital_assessor.rb
  app/services/assessors/liquid_capital_assessor.rb
  app/services/assessors/non_liquid_capital_assessor.rb
  app/services/assessors/vehicle_assessor.rb
  app/services/calculators/pensioner_capital_disregard_calculator.rb
  app/services/calculators/property_calculator.rb
  app/services/calculators/subject_matter_of_dispute_disregard_calculator.rb
  app/services/capital_collator_and_assessor.rb
  app/services/collators/capital_collator.rb
  app/services/workflows/non_passported_workflow.rb
  app/services/workflows/passported_workflow.rb
  spec/factories/partner_factory.rb
  spec/services/assessors/liquid_capital_assessor_spec.rb
  spec/services/assessors/non_liquid_capital_assessor_spec.rb
  spec/services/assessors/vehicle_assessor_spec.rb
  spec/services/calculators/pensioner_capital_disregard_calculator_spec.rb
  spec/services/calculators/property_calculator_spec.rb
  spec/services/calculators/subject_matter_of_dispute_disregard_calculator_spec.rb
  spec/services/collators/capital_collator_spec.rb
  spec/services/workflows/non_passported_workflow_spec.rb
  spec/services/workflows/passported_workflow_spec.rb
Labels: Approved

#23 EL-471: result payload additions
  app/services/capital_collator_and_assessor.rb
  app/services/decorators/v5/capital_result_decorator.rb
  app/services/decorators/v5/disposable_income_result_decorator.rb
  app/services/decorators/v5/gross_income_result_decorator.rb
  app/services/decorators/v5/vehicle_decorator.rb
  app/services/workflows/non_passported_workflow.rb
  db/migrate/20221123103859_add_combined_total_gross_income_to_gross_income_summary.rb
  db/schema.rb
  spec/services/decorators/v5/capital_result_decorator_spec.rb
  spec/services/decorators/v5/disposable_income_result_decorator_spec.rb
  spec/services/decorators/v5/gross_income_result_decorator_spec.rb
  spec/services/decorators/v5/vehicle_decorator_spec.rb
Labels: Approved

#25 EL-502: partner dependants
  app/lib/applicant_or_partner_wrapper.rb
  app/lib/person_wrapper.rb
  app/models/applicant_dependant.rb
  app/models/assessment.rb
  app/models/partner_dependant.rb
  app/services/calculators/childcare_eligibility_calculator.rb
  app/services/calculators/dependant_allowance_calculator.rb
  app/services/calculators/housing_costs_calculator.rb
  app/services/collators/childcare_collator.rb
  app/services/collators/dependants_allowance_collator.rb
  app/services/collators/outgoings_collator.rb
  app/services/collators/regular_outgoings_collator.rb
  app/services/concerns/childcare_eligibility.rb
  app/services/creators/dependants_creator.rb
  app/services/creators/eligibilities_creator.rb
  app/services/creators/gross_income_eligibility_creator.rb
  app/services/creators/partner_financials_creator.rb
  app/services/workflows/non_passported_workflow.rb
  db/migrate/20221124120203_add_type_to_dependants.rb
  db/schema.rb
  spec/requests/swagger_docs/v5/partner_financials_spec.rb
  spec/services/calculators/childcare_eligibility_calculator_spec.rb
  spec/services/calculators/dependant_allowance_calculator_spec.rb
  spec/services/collators/childcare_collator_spec.rb
  spec/services/collators/dependants_allowance_collator_spec.rb
  spec/services/collators/outgoings_collator_spec.rb
  spec/services/collators/regular_outgoings_collator_spec.rb
  spec/services/creators/eligibilities_creator_spec.rb
  spec/services/creators/gross_income_eligibility_creator_spec.rb
  spec/services/creators/partner_financials_creator_spec.rb
  swagger/v5/swagger.yaml
Labels: Approved

#26 EL-512: Add partner allowance into outgoings subtotal
  app/services/collators/disposable_income_collator.rb
  app/services/workflows/non_passported_workflow.rb
  spec/services/collators/disposable_income_collator_spec.rb
Labels: Approved

#24 reduce length of branch name used in url
  bin/uat_deploy
Labels: Approved

#27 EL-515: Stop trying to assess smod value prematurely
  app/services/calculators/subject_matter_of_dispute_disregard_calculator.rb
  app/services/capital_collator_and_assessor.rb
  app/services/collators/capital_collator.rb
  db/migrate/20221128152328_make_assessed_values_nullable.rb
  db/schema.rb
  features/disputed_assets/disputed_property.feature
  features/step_definitions/api_request.rb
  features/support/response_support_methods.rb
  spec/services/calculators/subject_matter_of_dispute_disregard_calculator_spec.rb
  spec/services/collators/capital_collator_spec.rb
Labels: Approved
