Repository ministryofjustice/check-financial-eligibility-partner, pull requests merged in 2023-02, with the labels that each got.

#71 employment calculator returns answer
  app/models/employment.rb
  app/services/calculators/employment_income_calculator.rb
  app/services/calculators/employment_income_result.rb
  app/services/calculators/multiple_employments_calculator.rb
  app/services/collators/disposable_income_collator.rb
  app/services/collators/gross_income_collator.rb
  app/services/utilities/employment_income_variation_checker.rb
  spec/models/employment_spec.rb
  spec/services/calculators/employment_income_calculator_spec.rb
  spec/services/calculators/multiple_employments_calculator_spec.rb
  spec/services/decorators/v5/disposable_income_result_decorator_spec.rb
  spec/services/utilities/employment_income_variation_checker_spec.rb
Labels: Approved

#75 EL-646: Allow month-frequency irregular payments
  app/constants/cfe_constants.rb
  app/models/irregular_income_payment.rb
  features/controlled_work/controlled_thresholds.feature
  public/schemas/irregular_incomes.json.erb
  spec/services/creators/partner_financials_creator_spec.rb
  swagger/v5/swagger.yaml
Labels: UAT, Approved

#72 EL-657: Move vehicle total out of the DB
  app/controllers/assessments_controller.rb
  app/lib/calculation_output.rb
  app/lib/capital_subtotals.rb
  app/lib/person_capital_subtotals.rb
  app/models/vehicle.rb
  app/services/assessors/vehicle_assessor.rb
  app/services/capital_collator_and_assessor.rb
  app/services/collators/capital_collator.rb
  app/services/decorators/v5/assessment_decorator.rb
  app/services/decorators/v5/capital_result_decorator.rb
  app/services/decorators/v5/result_summary_decorator.rb
  app/services/workflows/main_workflow.rb
  app/services/workflows/non_passported_workflow.rb
  app/services/workflows/passported_workflow.rb
  db/migrate/20230131154602_remove_total_vehicles_from_capital_summaries.rb
  db/schema.rb
  spec/requests/assessments_controller_spec.rb
  spec/services/assessors/vehicle_assessor_spec.rb
  spec/services/creators/assessment_creator_spec.rb
  spec/services/decorators/v5/assessment_decorator_spec.rb
  spec/services/decorators/v5/capital_result_decorator_spec.rb
  spec/services/workflows/passported_workflow_spec.rb
Labels: Approved

#77 Update system gems with sudo - otherwise it fails with permission denied
  .circleci/config.yml
Labels: Ready for review

#79 EL-658: Remove attributes from capital summary
  app/lib/calculation_output.rb
  app/lib/capital_subtotals.rb
  app/lib/person_capital_subtotals.rb
  app/services/assessors/capital_assessor.rb
  app/services/capital_collator_and_assessor.rb
  app/services/collators/capital_collator.rb
  app/services/decorators/v5/capital_result_decorator.rb
  app/services/decorators/v5/result_summary_decorator.rb
  app/services/remark_generators/orchestrator.rb
  app/services/remark_generators/residual_balance_checker.rb
  app/services/workflows/main_workflow.rb
  db/migrate/20230206104737_remove_columns_from_capital_summaries.rb
  db/migrate/20230206122959_remove_more_columns_from_capital_summaries.rb
  db/schema.rb
  spec/services/collators/capital_collator_spec.rb
  spec/services/creators/assessment_creator_spec.rb
  spec/services/decorators/v5/capital_result_decorator_spec.rb
  spec/services/remark_generators/orchestrator_spec.rb
  spec/services/remark_generators/residual_balance_checker_spec.rb
  spec/services/workflows/main_workflow_spec.rb
  spec/services/workflows/passported_workflow_spec.rb
Labels: Approved

#80 EL-676: Move model calculations
  app/models/concerns/monthly_equivalent_calculator.rb
  app/models/disposable_income_summary.rb
  app/models/employment.rb
  app/models/irregular_income_payment.rb
  app/models/other_income_source.rb
  app/models/property.rb
  app/models/state_benefit.rb
  app/services/assessors/property_assessor.rb
  app/services/assessors/vehicle_assessor.rb
  app/services/calculators/employment_income_calculator.rb
  app/services/calculators/employment_monthly_value_calculator.rb
  app/services/calculators/housing_costs_calculator.rb
  app/services/calculators/monthly_equivalent_calculator.rb
  app/services/calculators/monthly_income_converter.rb
  app/services/calculators/property_calculator.rb
  app/services/calculators/state_benefits_calculator.rb
  app/services/capital_collator_and_assessor.rb
  app/services/collators/capital_collator.rb
  app/services/collators/childcare_collator.rb
  app/services/collators/gross_income_collator.rb
  app/services/collators/legal_aid_collator.rb
  app/services/collators/maintenance_collator.rb
  spec/models/other_income_source_spec.rb
  spec/services/calculators/employment_income_calculator_spec.rb
  spec/services/calculators/employment_monthly_value_calculator_spec.rb
  spec/services/calculators/property_calculator_spec.rb
  spec/services/collators/capital_collator_spec.rb
Labels: Approved

#88 Docker image size reduced 785MB -> 169MB
  Dockerfile
Labels: Ready for review

#91 EL-720: Error message displayed when user submits eligibility check
  app/lib/calculation_output.rb
  features/partner/partner_assessment.feature
  features/step_definitions/api_request.rb
Labels: Ready for review

#87 All changes to 'classic' CFE since the fork
  .browserslistrc
  .circleci/config.yml
  .github/workflows/brakeman-analysis.yml
  .github/workflows/manual-integration-tests.yml
  .rubocop.yml
  .rubocop_todo.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  app/constants/cfe_constants.rb
  app/controllers/main_controller.rb
  app/models/proceeding_type.rb
  app/models/proceeding_type_threshold.rb
  app/services/legal_framework_api/query_service.rb
  config/environments/test.rb
  config/routes.rb
  public/schemas/proceeding_types.json.erb
  spec/factories/assessment_factory.rb
  spec/factories/proceeding_type_factory.rb
  spec/integration/policy_disregards_spec.rb
  spec/integration/remarks_spec.rb
  spec/integration/test_runner_spec.rb
  spec/integration/v5_full_assessment_spec.rb
  spec/models/gross_income_summary_spec.rb
  spec/models/proceeding_type_spec.rb
  spec/models/proceeding_type_threshold_spec.rb
  spec/rails_helper.rb
  spec/requests/applicants_controller_spec.rb
  spec/requests/assessments_controller_spec.rb
  spec/requests/main_controller_spec.rb
  spec/services/assessors/liquid_capital_assessor_spec.rb
  spec/services/assessors/main_assessor_spec.rb
  spec/services/calculators/disregarded_state_benefits_calculator_spec.rb
  spec/services/collators/childcare_collator_spec.rb
  spec/services/collators/disposable_income_collator_spec.rb
  spec/services/collators/gross_income_collator_spec.rb
  spec/services/collators/housing_costs_collator_spec.rb
  spec/services/collators/legal_aid_collator_spec.rb
  spec/services/collators/maintenance_collator_spec.rb
  spec/services/creators/assessment_creator_spec.rb
  spec/services/creators/disposable_income_eligibiltiy_creator_spec.rb
  spec/services/decorators/v5/assessment_decorator_spec.rb
  spec/services/legal_framework_api/query_service_spec.rb
  spec/services/remark_generators/orchestrator_spec.rb
  spec/services/remark_generators/residual_balance_checker_spec.rb
  spec/services/remarks_spec.rb
  spec/spec_helper.rb
Labels: Approved

#90 EL-702: Stop using Git-crypt
  .circleci/config.yml
  .gitattributes
  README.md
  bin/uat_deploy
  deploy/helm/templates/_envs.tpl
  deploy/helm/templates/secret.yaml
  deploy/helm/values-production.yaml
  deploy/helm/values-staging.yaml
  deploy/helm/values-uat.yaml
  deploy/helm/values/production.yaml
  deploy/helm/values/staging.yaml
  deploy/helm/values/uat.yaml
Labels: Approved

#83 EL-687: Remove attributes from gross income summary object
  app/lib/calculation_output.rb
  app/lib/capital_subtotals.rb
  app/lib/employment_income_subtotals.rb
  app/lib/gross_income_category_subtotals.rb
  app/lib/gross_income_subtotals.rb
  app/lib/person_capital_subtotals.rb
  app/lib/person_gross_income_subtotals.rb
  app/services/calculators/employment_income_calculator.rb
  app/services/calculators/employment_income_result.rb
  app/services/calculators/housing_costs_calculator.rb
  app/services/calculators/monthly_regular_transaction_amount_calculator.rb
  app/services/calculators/multiple_employments_calculator.rb
  app/services/collators/disposable_income_collator.rb
  app/services/collators/gross_income_collator.rb
  app/services/collators/regular_income_collator.rb
  app/services/collators/regular_outgoings_collator.rb
  app/services/concerns/monthly_equivalent_calculatable.rb
  app/services/decorators/v5/assessment_decorator.rb
  app/services/decorators/v5/disposable_income_result_decorator.rb
  app/services/decorators/v5/gross_income_decorator.rb
  app/services/decorators/v5/gross_income_result_decorator.rb
  app/services/decorators/v5/gross_income_summary_decorator.rb
  app/services/decorators/v5/result_summary_decorator.rb
  app/services/utilities/employment_income_monthly_equivalent_calculator.rb
  app/services/utilities/monthly_amount_converter.rb
  app/services/workflows/non_passported_workflow.rb
  db/migrate/20230209115454_remove_gross_income_summary_fields.rb
  db/schema.rb
  spec/factories/gross_income_summary_factory.rb
  spec/services/assessors/gross_income_assessor_spec.rb
  spec/services/calculators/state_benefits_calculator_spec.rb
  spec/services/collators/disposable_income_collator_spec.rb
  spec/services/collators/gross_income_collator_spec.rb
  spec/services/collators/regular_income_collator_spec.rb
  spec/services/concerns/monthly_equivalent_calculatable_spec.rb
  spec/services/decorators/v5/assessment_decorator_spec.rb
  spec/services/decorators/v5/disposable_income_result_decorator_spec.rb
  spec/services/decorators/v5/gross_income_decorator_spec.rb
  spec/services/decorators/v5/gross_income_result_decorator_spec.rb
  spec/services/decorators/v5/gross_income_summary_decorator_spec.rb
  spec/services/decorators/v5/state_benefit_decorator_spec.rb
  spec/services/utilities/employment_income_monthly_equivalent_calculator_spec.rb
  spec/services/utilities/monthly_amount_converter_spec.rb
  spec/services/workflows/main_workflow_spec.rb
Labels: Approved

#96 .gitignore comment tidy
  .gitignore
Labels: Approved

#98 EL-719: Reduce threshold for clearing out old assessments
  app/constants/cfe_constants.rb
Labels: Approved

#97 EL-721: Enable Sentry in all environments
  deploy/helm/values/production.yaml
  deploy/helm/values/staging.yaml
  deploy/helm/values/uat.yaml
Labels: Approved

#84 EL-695 capital thresholds for Immigration and Asylum first-tier tribunal
  app/constants/cfe_constants.rb
  app/services/creators/capital_eligibility_creator.rb
  config/thresholds/2022-04-11.yml
  features/controlled_work/controlled_thresholds.feature
  features/step_definitions/api_request.rb
  spec/requests/v2/assessments_controller_spec.rb
  spec/services/workflows/non_passported_workflow_spec.rb
  swagger/v5/swagger.yaml
Labels: Approved

#89 EL-701: Asylum support flow
  app/constants/cfe_constants.rb
  app/services/assessors/assessment_proceeding_type_assessor.rb
  app/services/workflows/main_workflow.rb
  db/migrate/20230215110407_add_receives_asylum_support_to_applicants.rb
  db/schema.rb
  features/upper_tribunal/asylum_support.feature
  public/schemas/applicant_v5.json.erb
  spec/requests/swagger_docs/v5/applicants_spec.rb
  spec/services/assessors/assessment_proceeding_type_assessor_spec.rb
  spec/services/creators/applicant_creator_spec.rb
  spec/services/workflows/main_workflow_spec.rb
  swagger/v5/swagger.yaml
Labels: Approved

#101 rename 'standard' to 'certificated' in cucumber tests
  features/disputed_assets/disputed_capital_items.feature
  features/disputed_assets/disputed_property.feature
  features/disputed_assets/disputed_vehicle.feature
  features/partner/partner_assessment.feature
  features/step_definitions/api_request.rb
Labels: Approved

#104 EL-638: Ignore LFAPI for upper tribunal matter types
  app/services/legal_framework_api/mock_threshold_waivers.rb
  app/services/utilities/proceeding_type_threshold_populator.rb
  spec/services/legal_framework_api/mock_threshold_waivers_spec.rb
  spec/services/utilities/proceeding_type_threshold_populator_spec.rb
Labels: Approved

#105 EL-747 new SMOD calculations - before other disregards
  app/models/capital_summary.rb
  app/services/assessors/property_assessor.rb
  app/services/assessors/vehicle_assessor.rb
  app/services/calculators/property_calculator.rb
  app/services/calculators/subject_matter_of_dispute_disregard_calculator.rb
  app/services/collators/capital_collator.rb
  app/services/decorators/v5/property_decorator.rb
  config/thresholds/2019-04-08.yml
  config/thresholds/2020-04-06.yml
  config/thresholds/2021-01-28.yml
  db/migrate/20230224091833_remove_allowable_outstanding_mortgage.rb
  db/schema.rb
  features/disputed_assets/disputed_capital_items.feature
  features/disputed_assets/disputed_property.feature
  features/disputed_assets/disputed_vehicle.feature
  spec/requests/v2/assessments_controller_spec.rb
  spec/services/calculators/property_calculator_spec.rb
  spec/services/calculators/subject_matter_of_dispute_disregard_calculator_spec.rb
  spec/services/collators/capital_collator_spec.rb
  spec/services/decorators/v5/property_decorator_spec.rb
Labels: Approved
