Repository ministryofjustice/check-financial-eligibility-partner, pull requests merged in 2023-03, with the labels that each got.

#100 EL-704 upper tribunal certificated thresholds
  app/services/creators/capital_eligibility_creator.rb
  app/services/creators/disposable_income_eligibility_creator.rb
  config/thresholds/2022-04-11.yml
  features/upper_tribunal/asylum_support.feature
  spec/services/creators/capital_eligibility_creator_spec.rb
  spec/services/creators/disposable_income_eligibiltiy_creator_spec.rb
Labels: UAT, Approved

#108 EL-710: Replace custom date validator with a standard gem
  Gemfile
  Gemfile.lock
  app/models/outgoings/base_outgoing.rb
  app/models/partner.rb
  app/models/state_benefit_payment.rb
  app/models/vehicle.rb
  app/validators/cfe_date_validator.rb
  config/locales/en.yml
  spec/spec_helper.rb
  spec/validators/cfe_date_validator_spec.rb
Labels: Approved

#110 EL-765 expose pensioner disregard in capital section
  app/lib/person_capital_subtotals.rb
  app/services/collators/capital_collator.rb
  app/services/decorators/v5/capital_result_decorator.rb
  features/pensioner/pensioner_disregard.feature
  features/step_definitions/api_request.rb
  spec/requests/swagger_docs/v5/full_assessment_spec.rb
  spec/requests/v2/assessments_controller_spec.rb
  spec/services/collators/capital_collator_spec.rb
  spec/services/decorators/v5/capital_result_decorator_spec.rb
  swagger/v5/swagger.yaml
Labels: Approved

#109 EL-710: Proceeding types decorator simplification
  app/services/decorators/v5/capital_result_decorator.rb
  app/services/decorators/v5/disposable_income_result_decorator.rb
  app/services/decorators/v5/gross_income_result_decorator.rb
  app/services/decorators/v5/proceeding_types_result_decorator.rb
  app/services/decorators/v5/result_summary_decorator.rb
  spec/services/decorators/v5/proceeding_types_result_decorator_spec.rb
  spec/spec_helper.rb
Labels: Approved

#102 EL-723 Part One - synonyms 'level of help' and 'level of representation'
  app/models/assessment.rb
  app/services/assessors/property_assessor.rb
  app/services/calculators/property_calculator.rb
  app/services/capital_collator_and_assessor.rb
  app/services/collators/capital_collator.rb
  app/services/creators/assessment_creator.rb
  app/services/creators/capital_eligibility_creator.rb
  app/services/creators/disposable_income_eligibility_creator.rb
  app/services/utilities/proceeding_type_threshold_populator.rb
  config/initializers/inflections.rb
  db/migrate/20230225142836_rename_level_of_representation.rb
  db/schema.rb
  features/step_definitions/api_request.rb
  public/schemas/assessment.json.erb
  spec/requests/swagger_docs/v5/assessments_spec.rb
  spec/requests/swagger_docs/v5/full_assessment_spec.rb
  spec/services/calculators/property_calculator_spec.rb
  spec/services/collators/capital_collator_spec.rb
  spec/services/creators/assessment_creator_spec.rb
  spec/services/creators/capital_eligibility_creator_spec.rb
  spec/services/creators/disposable_income_eligibiltiy_creator_spec.rb
  spec/services/utilities/proceeding_type_threshold_populator_spec.rb
  spec/services/workflows/non_passported_workflow_spec.rb
  swagger/v5/swagger.yaml
Labels: UAT, Approved

#116 EL-710 Remove nil checks and safe navigation operators where they are superflouous
  app/models/api_response.rb
  app/services/decorators/v5/capital_decorator.rb
  app/services/decorators/v5/remarks_decorator.rb
  spec/models/api_response_spec.rb
  spec/spec_helper.rb
Labels: Approved

#103 EL-722: Rules governing statutory sick/maternity pay
  app/services/calculators/employment_income_calculator.rb
  app/services/creators/employments_creator.rb
  db/migrate/20230215110407_add_receives_asylum_support_to_applicants.rb
  db/migrate/20230223153716_add_receiving_only_statutory_sick_or_maternity_pay_to_employments.rb
  db/schema.rb
  features/employment/statutory_pay.feature
  features/step_definitions/api_request.rb
  features/support/response_support_methods.rb
  public/schemas/employment.json.erb
  spec/requests/swagger_docs/v5/employments_spec.rb
  spec/requests/swagger_docs/v5/full_assessment_spec.rb
  spec/services/calculators/employment_income_calculator_spec.rb
  spec/services/creators/employments_creator_spec.rb
  swagger/v5/swagger.yaml
Labels: UAT, Approved

#112 EL-768: Expose property subject matter of dispute calculation
  app/lib/person_capital_subtotals.rb
  app/lib/property_subtotals.rb
  app/services/assessors/property_assessor.rb
  app/services/calculators/property_calculator.rb
  app/services/collators/capital_collator.rb
  app/services/decorators/v5/assessment_decorator.rb
  app/services/decorators/v5/capital_decorator.rb
  app/services/decorators/v5/property_decorator.rb
  app/services/decorators/v5/result_summary_decorator.rb
  config/thresholds/2022-04-11.yml
  spec/integration/v5_full_assessment_spec.rb
  spec/requests/swagger_docs/v5/capitals_spec.rb
  spec/requests/swagger_docs/v5/full_assessment_spec.rb
  spec/requests/swagger_docs/v5/partner_financials_spec.rb
  spec/requests/v2/assessments_controller_spec.rb
  spec/services/calculators/property_calculator_spec.rb
  spec/services/collators/capital_collator_spec.rb
  spec/services/decorators/v5/property_decorator_spec.rb
  spec/swagger_helper.rb
  swagger/v5/swagger.yaml
Labels: Approved

#113 EL-767 Expose total capital after SMOD disregard applied
  app/lib/person_capital_subtotals.rb
  app/services/collators/capital_collator.rb
  app/services/decorators/v5/capital_result_decorator.rb
  spec/requests/swagger_docs/v5/full_assessment_spec.rb
  spec/requests/v2/assessments_controller_spec.rb
  spec/services/decorators/v5/capital_result_decorator_spec.rb
  swagger/v5/swagger.yaml
Labels: Approved

#111 El 746: Liveness probe checks that the schema is loaded
  app/controllers/status_controller.rb
  config/routes.rb
  deploy/helm/templates/deployment_web.yaml
Labels: Approved

#117 Lep 1 upgrade ruby in cfe p
  .circleci/config.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: Approved

#118 EL-710 add undercover to prevent coverage regressions
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  spec/spec_helper.rb
Labels: Approved

#119 EL-737 convert JSON date formatting for format: :string, type: :date
  public/schemas/applicant_v5.json.erb
  public/schemas/assessment.json.erb
  public/schemas/cash_transaction.json.erb
  public/schemas/common.json
  public/schemas/dependants.json.erb
  public/schemas/employment.json.erb
  public/schemas/other_incomes.json.erb
  public/schemas/outgoings.json.erb
  public/schemas/state_benefits.json.erb
  public/schemas/vehicles.json.erb
  spec/requests/applicants_controller_spec.rb
  spec/requests/v2/assessments_controller_spec.rb
  spec/validators/json_validator_spec.rb
Labels: Approved

#121 EL-710 remove obvious redundant nil checks
  app/services/calculators/housing_costs_calculator.rb
  app/services/creators/partner_properties_creator.rb
  app/services/creators/state_benefits_creator.rb
  spec/services/collators/outgoings_collator_spec.rb
  spec/spec_helper.rb
Labels: Approved

#123 EL-710 remove redundant nil checks in Remarks Orchestrator
  app/services/remark_generators/frequency_checker.rb
  app/services/remark_generators/orchestrator.rb
  spec/spec_helper.rb
Labels: Approved

#106 Bundler 2.4
  Gemfile.lock
Labels: Approved

#124 Fix "rugged" gem install
  README.md
Labels: Approved

#126 LEP-28 replace custom rescue_from with gem version
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  spec/requests/application_controller_spec.rb
Labels: Approved

#127 EL-710 Fix up spec that was crashing but not checked for success
  spec/requests/cash_transactions_controller_spec.rb
Labels: Approved

#115 EL-739 remove net employment input
  app/controllers/application_controller.rb
  app/controllers/employments_controller.rb
  app/models/employment_payment.rb
  app/services/creators/employments_creator.rb
  app/services/creators/full_assessment_creator.rb
  app/services/creators/partner_financials_creator.rb
  lib/integration_helpers/test_case/employment_collection.rb
  public/schemas/employment.json.erb
  spec/fixtures/employments.json
  spec/fixtures/partner_financials.json
  spec/integration_helpers/test_case/employment_collection_spec.rb
  spec/models/employment_payment_spec.rb
  spec/requests/employments_controller_spec.rb
  spec/requests/swagger_docs/v5/employments_spec.rb
  spec/requests/swagger_docs/v5/full_assessment_spec.rb
  spec/requests/swagger_docs/v5/partner_financials_spec.rb
  spec/services/creators/employments_creator_spec.rb
  spec/services/creators/partner_financials_creator_spec.rb
  spec/swagger_helper.rb
  swagger/v5/swagger.yaml
Labels: Approved

#120 EL-734 call single-shot API via cucumber
  Gemfile
  Gemfile.lock
  features/client_income/unspecified_source_income.feature
  features/controlled_work/controlled_thresholds.feature
  features/controlled_work/property_assessment.feature
  features/disputed_assets/disputed_capital_items.feature
  features/disputed_assets/disputed_property.feature
  features/disputed_assets/disputed_vehicle.feature
  features/partner/partner_assessment.feature
  features/pensioner/pensioner_disregard.feature
  features/step_definitions/api_request.rb
  features/support/response_support_methods.rb
Labels: Approved

#134 LEP-49 Pensioner disregard split across client and partner assets
  app/services/capital_collator_and_assessor.rb
  app/services/decorators/v5/capital_result_decorator.rb
  features/partner/partner_assessment.feature
  features/pensioner/pensioner_disregard.feature
  features/step_definitions/api_request.rb
  features/support/response_support_methods.rb
  spec/requests/v2/assessments_controller_spec.rb
Labels: Approved

#136 EL-710 - standardise handling of calls to Legal Framework API
  app/services/legal_framework_api/response_error.rb
  app/services/legal_framework_api/threshold_waivers.rb
  config/environments/test.rb
  spec/cassettes/LegalFrameworkAPI_ThresholdWaivers/_call/successful_API_call/responds_to_calling_service_with_parsed_response.yml
  spec/services/legal_framework_api/response_error_spec.rb
  spec/services/legal_framework_api/threshold_waivers_spec.rb
Labels: Approved

#135 Fix-up test refactoring
  features/step_definitions/api_request.rb
Labels: Approved

#133 EL-710 - tax/NI refund calculator
  app/controllers/application_controller.rb
  spec/services/calculators/tax_ni_refund_calculator_spec.rb
  spec/spec_helper.rb
Labels: Approved

#132 LEP-46 - add non-property disputed assets allowance figure
  app/lib/person_capital_subtotals.rb
  app/services/collators/capital_collator.rb
  app/services/decorators/v5/capital_result_decorator.rb
  features/disputed_assets/disputed_property.feature
  features/disputed_assets/multiple_disputed_assets.feature
  spec/requests/swagger_docs/v5/full_assessment_spec.rb
  spec/requests/v2/assessments_controller_spec.rb
  spec/services/decorators/v5/capital_result_decorator_spec.rb
  swagger/v5/swagger.yaml
Labels: Approved

#125 LEP-17 Run spreadsheet examples through single-shot API
  app/controllers/irregular_incomes_controller.rb
  app/services/creators/full_assessment_creator.rb
  app/services/creators/irregular_income_creator.rb
  app/services/creators/other_incomes_creator.rb
  app/services/creators/outgoings_creator.rb
  app/services/creators/partner_financials_creator.rb
  app/services/creators/proceeding_types_creator.rb
  features/CCC_CFE_Integration_Test_V3/NPE10-4-V5.feature
  lib/integration_helpers/test_case/worksheet.rb
  spec/integration/test_runner_spec.rb
  spec/requests/outgoings_controller_spec.rb
  spec/requests/swagger_docs/v5/outgoings_spec.rb
  spec/services/creators/irregular_income_creator_spec.rb
  spec/services/creators/outgoings_creator_spec.rb
  spec/spec_helper.rb
Labels: Approved

#131 Lep 42 expose allowances for properties
  app/services/assessors/property_assessor.rb
  app/services/calculators/property_calculator.rb
  app/services/utilities/number_utilities.rb
  features/disputed_assets/disputed_property.feature
  features/disputed_assets/multiple_disputed_assets.feature
  features/partner/partner_assessment.feature
  features/property/property.feature
  spec/integration/v5_full_assessment_spec.rb
  spec/requests/v2/assessments_controller_spec.rb
  spec/services/calculators/property_calculator_spec.rb
  spec/swagger_helper.rb
  swagger/v5/swagger.yaml
Labels: Approved

#137 EL-710 remove old cassettes
  spec/cassettes/Decorators_V4_DisposableIncomeResultDecorator/_as_json/returns_the_expected_structure.yml
  spec/cassettes/V3_Assessments/assessments/_id_/get/successful/returns_a_200_response.yml
  spec/cassettes/V3_Assessments/assessments/post/successful/returns_a_200_response.yml
  spec/cassettes/V4_Assessments/assessments/_id_/get/successful/returns_a_200_response.yml
  spec/cassettes/V4_Assessments/assessments/post/Unprocessable_Entity/returns_a_422_response.yml
  spec/cassettes/V4_Assessments/assessments/post/successful/returns_a_200_response.yml
  spec/cassettes/V5_Assessments/assessments/_id_/get/successful/returns_a_200_response.yml
  spec/cassettes/V5_Assessments/assessments/post/successful/returns_a_200_response.yml
  spec/integration/v5_full_assessment_spec.rb
Labels: Approved

#129 LEP-19: Remove level_of_representation synonym for level_of_help
  app/services/creators/assessment_creator.rb
  public/schemas/assessment.json.erb
  spec/requests/swagger_docs/v5/assessments_spec.rb
  spec/services/creators/assessment_creator_spec.rb
  swagger/v5/swagger.yaml
Labels: Approved

#139 Lep 51 pensioner disregard with smod
  app/services/collators/capital_collator.rb
  features/disputed_assets/disputed_pensioner_assets.feature
Labels: Ready for review

#142 LEP 53 FIX main home equity disregard
  app/services/calculators/property_calculator.rb
  app/services/collators/capital_collator.rb
  features/disputed_assets/disputed_property.feature
  features/disputed_assets/disputed_vehicle.feature
  features/disputed_assets/multiple_disputed_assets.feature
  features/partner/partner_assessment.feature
  spec/services/calculators/property_calculator_spec.rb
  spec/services/decorators/v5/property_decorator_spec.rb
Labels: Ready for review

#143 LEP-53: tidy up functions and variable names
  app/services/calculators/property_calculator.rb
Labels: Approved

#140 EL-710 Remove redundant schema definitions
  public/schemas/assessment_request.json
  public/schemas/assessment_response.json
  public/schemas/capital.json
  public/schemas/dependant.json
  public/schemas/properties.json
  spec/rails_helper.rb
  spec/services/creators/assessment_creator_spec.rb
Labels: Approved

#141 LEP-27 Validate API requests using swagger schema
  app/services/creators/capitals_creator.rb
  app/validators/json_swagger_validator.rb
  features/support/request_support_methods.rb
  public/schemas/capital.json.erb
  spec/integration/policy_disregards_spec.rb
  spec/integration/v5_full_assessment_spec.rb
  spec/requests/capitals_controller_spec.rb
  spec/requests/swagger_docs/v5/capitals_spec.rb
  spec/requests/swagger_docs/v5/full_assessment_spec.rb
  spec/requests/swagger_docs/v5/partner_financials_spec.rb
  spec/services/creators/capitals_creator_spec.rb
  spec/swagger_helper.rb
  swagger/v5/swagger.yaml
Labels: Approved

#144 LEP-27 - spike moving schema validation to controller
  app/controllers/capitals_controller.rb
  app/services/creators/capitals_creator.rb
  app/services/creators/full_assessment_creator.rb
  app/services/creators/partner_financials_creator.rb
  spec/services/creators/capitals_creator_spec.rb
Labels: Approved

#148 LEP-59: remove (unused) combined_capital_contribution field
  app/services/decorators/v5/capital_result_decorator.rb
  spec/requests/swagger_docs/v5/full_assessment_spec.rb
  spec/requests/v2/assessments_controller_spec.rb
  spec/services/decorators/v5/capital_result_decorator_spec.rb
  swagger/v5/swagger.yaml
Labels: Approved

#145 LEP-54 change partner and dependant thresholds for 10th April 2023
  config/thresholds/2023-04-10.yml
  config/thresholds/values.yml
  features/partner/partner_assessment.feature
  features/step_definitions/api_request.rb
  features/support/response_support_methods.rb
Labels: Approved

#149 LEP-59: Allocate partner allowance to client not to partner
  app/services/workflows/non_passported_workflow.rb
  features/partner/partner_assessment.feature
  spec/requests/v2/assessments_controller_spec.rb
Labels: Approved

#152 LEP-27 move schema validation up to controller
  app/controllers/capitals_controller.rb
  app/services/creators/capitals_creator.rb
  app/services/creators/full_assessment_creator.rb
  app/services/creators/partner_financials_creator.rb
  public/schemas/capitals.json.erb
  spec/services/creators/capitals_creator_spec.rb
Labels: Approved

#156 LEP-63 Part I - improve controller test
  spec/rails_helper.rb
  spec/requests/v2/assessments_controller_spec.rb
Labels: Approved

#138 LEP-8 fixed a typo housing_costs_type should be housing_cost_type, up…
  README.md
  app/constants/cfe_constants.rb
  spec/requests/swagger_docs/v5/full_assessment_spec.rb
  spec/requests/swagger_docs/v5/outgoings_spec.rb
  swagger/v5/swagger.yaml
Labels: question

#158 LEP-63 improve cash_transactions spec
  spec/requests/v2/assessments_controller_spec.rb
Labels: Approved

#160 LEP-63 remove unused decorator
  app/services/concerns/transactions.rb
  app/services/decorators/v5/disposable_income_summary_decorator.rb
  app/services/decorators/v5/gross_income_decorator.rb
  spec/services/decorators/v5/disposable_income_summary_decorator_spec.rb
Labels: Approved

#163 Update cloud-platform-tools image to fix circle deploy
  .circleci/config.yml
Labels: Approved

#161 LEP-63 give subtotals object a small amount of behaviour
  app/lib/gross_income_subtotals.rb
  app/services/decorators/v5/gross_income_result_decorator.rb
  app/services/decorators/v5/result_summary_decorator.rb
  app/services/workflows/non_passported_workflow.rb
  spec/services/decorators/v5/assessment_decorator_spec.rb
Labels: Approved

#164 LEP-61 refactor cucumber test infrastructure
  features/controlled_work/controlled_thresholds.feature
  features/controlled_work/property_assessment.feature
  features/disputed_assets/disputed_capital_items.feature
  features/disputed_assets/disputed_pensioner_assets.feature
  features/disputed_assets/disputed_property.feature
  features/disputed_assets/disputed_vehicle.feature
  features/disputed_assets/multiple_disputed_assets.feature
  features/partner/partner_assessment.feature
  features/pensioner/pensioner_disregard.feature
  features/property/property.feature
  features/step_definitions/api_request.rb
Labels: Approved

#155 LEP-63 Part II move updating of disposable_income_summary up the call stack
  app/services/calculators/housing_costs_calculator.rb
  app/services/collators/childcare_collator.rb
  app/services/collators/dependants_allowance_collator.rb
  app/services/collators/housing_costs_collator.rb
  app/services/collators/legal_aid_collator.rb
  app/services/collators/maintenance_collator.rb
  app/services/collators/outgoings_collator.rb
  app/services/decorators/v5/disposable_income_decorator.rb
  spec/services/collators/childcare_collator_spec.rb
  spec/services/collators/dependants_allowance_collator_spec.rb
  spec/services/collators/disposable_income_collator_spec.rb
  spec/services/collators/housing_costs_collator_spec.rb
  spec/services/collators/legal_aid_collator_spec.rb
  spec/services/collators/maintenance_collator_spec.rb
  spec/services/collators/outgoings_collator_spec.rb
  spec/services/utilities/employment_income_monthly_equivalent_calculator_spec.rb
  spec/services/workflows/non_passported_workflow_spec.rb
  spec/spec_helper.rb
Labels: Approved

#168 LEP-48 exposed level_of_help in response from API
  app/services/decorators/v5/assessment_decorator.rb
  spec/requests/swagger_docs/v5/full_assessment_spec.rb
  spec/requests/v2/assessments_controller_spec.rb
  spec/services/decorators/v5/assessment_decorator_spec.rb
  swagger/v5/swagger.yaml
Labels: Approved

#165 LEP-22 Stop persisting employment values in disposable_income_summary
  app/lib/employment_income_subtotals.rb
  app/services/collators/disposable_income_collator.rb
  app/services/collators/gross_income_collator.rb
  app/services/decorators/v5/disposable_income_result_decorator.rb
  app/services/workflows/non_passported_workflow.rb
  db/migrate/20230324150833_remove_employment_from_disposable_income.rb
  db/schema.rb
  spec/services/collators/disposable_income_collator_spec.rb
  spec/services/collators/gross_income_collator_spec.rb
  spec/services/decorators/v5/disposable_income_result_decorator_spec.rb
Labels: Approved

#167 LEP-22 Remove dependant allowance from disposable_income_summary
  app/lib/calculation_output.rb
  app/lib/disposable_income_subtotals.rb
  app/services/collators/disposable_income_collator.rb
  app/services/collators/outgoings_collator.rb
  app/services/decorators/v5/assessment_decorator.rb
  app/services/decorators/v5/deductions_decorator.rb
  app/services/decorators/v5/disposable_income_decorator.rb
  app/services/decorators/v5/disposable_income_result_decorator.rb
  app/services/decorators/v5/result_summary_decorator.rb
  app/services/workflows/non_passported_workflow.rb
  db/migrate/20230327082347_remove_dependant_allowance.rb
  db/schema.rb
  spec/factories/disposable_income_summary_factory.rb
  spec/services/collators/disposable_income_collator_spec.rb
  spec/services/decorators/v5/deductions_decorator_spec.rb
  spec/services/decorators/v5/disposable_income_result_decorator_spec.rb
Labels: Approved

#170 LEP-81 Add outgoings to partner financials endpoint
  app/controllers/outgoings_controller.rb
  app/services/creators/full_assessment_creator.rb
  app/services/creators/outgoings_creator.rb
  app/services/creators/partner_financials_creator.rb
  spec/fixtures/partner_financials.json
  spec/requests/partner_financials_controller_spec.rb
  spec/requests/swagger_docs/v5/cash_transactions_spec.rb
  spec/requests/swagger_docs/v5/full_assessment_spec.rb
  spec/requests/swagger_docs/v5/outgoings_spec.rb
  spec/requests/swagger_docs/v5/partner_financials_spec.rb
  spec/requests/v2/assessments_controller_spec.rb
  spec/services/creators/outgoings_creator_spec.rb
  spec/services/creators/partner_financials_creator_spec.rb
  spec/swagger_helper.rb
  swagger/v5/swagger.yaml
Labels: Approved

#173 LEP-6: Remove property calculations from database table
  app/services/calculators/property_calculator.rb
  db/migrate/20230329105231_remove_property_results.rb
  db/schema.rb
  spec/services/calculators/subject_matter_of_dispute_disregard_calculator_spec.rb
  spec/services/decorators/v5/property_decorator_spec.rb
Labels: Approved

#172 LEP-77: Fix partner financials documentation bug
  spec/requests/swagger_docs/v5/partner_financials_spec.rb
  spec/swagger_helper.rb
  swagger/v5/swagger.yaml
Labels: Approved

#175 LEP-60 Add guard support
  Gemfile
  Gemfile.lock
  Guardfile
  README.md
Labels: Approved
